/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Biseccion */

#ifndef _Included_Biseccion
#define _Included_Biseccion
#ifdef __cplusplus
extern "C"
{

#endif
  /*
   * Class:     Biseccion
   * Method:    resolver
   * Signature: (DD)LBiseccion/ResultadoBiseccion;
   */
  JNIEXPORT jobject JNICALL Java_Biseccion_resolver(JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
